### ISSUE TITLE
start_monitor() not working if run after game is launched

### ISSUE THREAD

**Issue by Kalmat** [Andrey1994/game_overlay_sdk#13]
Hi! Thank you for this module! It's not easy at all to find a way to work with overlays using python.

I'm developing a very simple tool to monitor system values like CPU usage, CPU temp, Disk usage, RAM usage, GPU usage, GPU temp, GPU fan. It also has a FPS counter to check in-game performance but, in case the game is in directdraw exclusive mode, it hides my window, making it useless. I've been testing your module in order to send messages with these values to the overlay, so it's not obscured by the game. It works fine when I use `run_process()` method, but I got some issues when I use `start_monitor()` method. Using run_process() is not the best option in my case, since these launchers also check if the game has been run from outside, it's harder for the users to know the full path, etc. (i'm using pywinctl module to detect the active process, so it's very easy to hook to that process once it's started, and then monitor it... no need for the user to know anything else, this is why I do prefer the `start_monitor()` method. Perhaps it's also a good option in your case to avoid command-line inputs. You can give it a try if you think it's worth)

As an example, I tried this (from python/examples folder):

`python3 monitor.py --name "Vanguard.exe"`

If the script is executed before launching the game, it tries to inject the DLL, but the launcher (battle.net in this case) detects it and stops the launching, throwing an error. If the script is executed after launching the game, it continuously outputs `"WARNING:root:target process is not created`. Do you think there is a way to make it work after launching the game, so the launcher doesn't detect it has been "injected"? 

Besides, is it possible to modify the overlay in terms of size and position, font size or color, text alignment, number of visible text rows or things like these?

And finally, sorry for abusing your time, do you know if the overlay has its own window handle, so you can address it from other programs? If so, I was thinking if it was possible to use it to draw some other things (I mean, the whole monitor thing) apart from just text messages... do you think this could be feasible in any way?

Thank you so much in advance!

**Comment by Andrey1994** [comment]
Hi.

>> And finally, sorry for abusing your time, do you know if the overlay has its own window handle, so you can address it from other programs? If so, I was thinking if it was possible to use it to draw some other things (I mean, the whole monitor thing) apart from just text messages... do you think this could be feasible in any way?

no, it renders it inside the game window, its possible to add charts there but it requires changes in C++ code for rendering

>> Besides, is it possible to modify the overlay in terms of size and position, font size or color, text alignment, number of visible text rows or things like these?

Yes, but need to change C++ part inside the library

>> If the script is executed before launching the game, it tries to inject the DLL, but the launcher (battle.net in this case) detects it and stops the launching, throwing an error. If the script is executed after launching the game, it continuously outputs "WARNING:root:target process is not created. Do you think there is a way to make it work after launching the game, so the launcher doesn't detect it has been "injected"

I know there are some limitations with it and actually the approach I used to check if process is created is not perfect. Its one of the reasons why there is an option to use `run_process`


I am not actively supporting this library right now, I am considering an option to remake it completely with much more options and UI elements but it will not be open sourced

**Comment by Kalmat** [comment]
Thank you so much for your prompt reply! I will take a look to your "new" module in case you eventually decide to build it. The System Monitor I'm building is mainly for fun and personal use, but I do like to do things as good as possible.

Check [PyWinCtl](https://github.com/Kalmat/PyWinCtl) to verify if it can be useful for you in order to deal with foreign windows and apps. With it, you can get all or specific windows and apps on screen, manipulate them, get some additional info, and even define a watchdog to be notified when its status change. I can also add some new features that you may require.

Thank you again, and good luck with your projects!
