### ISSUE TITLE
GENERAL_ERROR:4 failed to run process please check logs

### ISSUE THREAD

**Issue by NikTink** [Andrey1994/game_overlay_sdk#3]
running the steam example only results in the following error upon calling `game_overlay_sdk.injector.run_process:`:

> game_overlay_sdk.injector.InjectionError: GENERAL_ERROR:4 failed to run process please check logs

An empty log file is generated in the root folder.

command line 
`python test1.py --exe_path "C:\Program Files (x86)\Steam\steamapps\common\Shadow of the Tomb Raider Trial\SOTTR.exe" --steam_app_id 974630`

**Comment by Andrey1994** [comment]
- test1.py means this https://github.com/Andrey1994/game_overlay_sdk/blob/master/python/examples/create.py ?
- logs from this part of execution should be in stderr, to get more logs you can call enable_dev_logger instead https://github.com/Andrey1994/game_overlay_sdk/blob/master/python/examples/create.py#L41 
- Did you run it with admin privilegies?
- Could you share full output(stderr+stdout)?

**Comment by NikTink** [comment]
you cant exactly run a python script with admin privileges, but the command prompt this was called from was launched with admin privileges

And yes, all references to "test1" mean the create.py example.

 enable_dev_logger is enabled here:

here is the full output(line numbers dont hold true):
```
[2019-08-25 19:24:28.481] [monitorLogger] [info] Trying to start executable C:\Program Files (x86)\Steam\steamapps\common\Shadow of the Tomb Raider Trial\SOTTR.exe with args:
[2019-08-25 19:24:28.485] [monitorLogger] [error] failed to create maped file Error 5
Traceback (most recent call last):
  File "test1.py", line 56, in <module>
    main ()
  File "test1.py", line 43, in main
    game_overlay_sdk.injector.run_process (args.exe_path, args.exe_args, args.steam_app_id)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\game_overlay_sdk\injector.py", line 158, in run_process
    raise InjectionError ('failed to run process please check logs', res)
game_overlay_sdk.injector.InjectionError: GENERAL_ERROR:4 failed to run process please check logs
[2019-08-25 19:24:28.526] [monitorLogger] [trace] releasing
[2019-08-25 19:24:28.526] [monitorLogger] [trace] releasing
```

**Comment by Andrey1994** [comment]
it failed to create shared file here https://github.com/Andrey1994/game_overlay_sdk/blob/master/src/DLLInjection/Monitor.cpp#L111 
GetLastError code 5 means access is denied https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

So there are 3 possible issues:
- no admin priviligies(but you run it with admin cmd so it's not an option here)
- maybe previous execution did not close this file correctly(its very unlikely) but to check it you can try to restart PC and run again
- https://stackoverflow.com/questions/3999157/system-error-0x5-createfilemapping seems like there should be SeCreateGlobalPrivilege. I have this priv enabled - cmd to check
```
C:\WINDOWS\system32>whoami /priv

PRIVILEGES INFORMATION
----------------------

Privilege Name                            Description                                                        State
========================================= ================================================================== ========
SeIncreaseQuotaPrivilege                  Adjust memory quotas for a process                                 Disabled
SeSecurityPrivilege                       Manage auditing and security log                                   Disabled
SeTakeOwnershipPrivilege                  Take ownership of files or other objects                           Disabled
SeLoadDriverPrivilege                     Load and unload device drivers                                     Disabled
SeSystemProfilePrivilege                  Profile system performance                                         Disabled
SeSystemtimePrivilege                     Change the system time                                             Disabled
SeProfileSingleProcessPrivilege           Profile single process                                             Disabled
SeIncreaseBasePriorityPrivilege           Increase scheduling priority                                       Disabled
SeCreatePagefilePrivilege                 Create a pagefile                                                  Disabled
SeBackupPrivilege                         Back up files and directories                                      Disabled
SeRestorePrivilege                        Restore files and directories                                      Disabled
SeShutdownPrivilege                       Shut down the system                                               Disabled
SeDebugPrivilege                          Debug programs                                                     Disabled
SeSystemEnvironmentPrivilege              Modify firmware environment values                                 Disabled
SeChangeNotifyPrivilege                   Bypass traverse checking                                           Enabled
SeRemoteShutdownPrivilege                 Force shutdown from a remote system                                Disabled
SeUndockPrivilege                         Remove computer from docking station                               Disabled
SeManageVolumePrivilege                   Perform volume maintenance tasks                                   Disabled
SeImpersonatePrivilege                    Impersonate a client after authentication                          Enabled
SeCreateGlobalPrivilege                   Create global objects                                              Enabled
SeIncreaseWorkingSetPrivilege             Increase a process working set                                     Disabled
SeTimeZonePrivilege                       Change the time zone                                               Disabled
SeCreateSymbolicLinkPrivilege             Create symbolic links                                              Disabled
SeDelegateSessionUserImpersonatePrivilege Obtain an impersonation token for another user in the same session Disabled
```

**Comment by NikTink** [comment]
Problem resolved.

 Running cmd from the start menu "as administrator" does not actually run it as an administrator, but running a shortcut of cmd.exe when the "run as administrator" property is set... will run it as administrator. I mustve messed something up in my computer. PEBCAS

Thank you so much for the help!

**Comment by Andrey1994** [comment]
btw how are you going to use this lib?

**Comment by NikTink** [comment]
I was planning to use it for my project of throwing some server information ontop of a fullscreen game. This sort of failed though, as the game i was planning to use this for is launched through the anti-cheat software which blocks the library
