### ISSUE TITLE
Mac OSX Support / OpenGL renderer support

### ISSUE THREAD

**Issue by renegadeandy** [Andrey1994/game_overlay_sdk#5]
Hi,

Does this library work on Mac? Would it work for OpenGL games or just DirectX windows based games? 

Can we get mac & opengl support?

**Comment by Andrey1994** [comment]
Hi,

It supports Directx11/12 and Vulkan but only for Windows.

This library uses WinAPI for everything, so it will be really hard to port it to Linux or MacOS, also to support OpenGL a lot of work will be required to hook OpenGL calls.(for Vulkan its easier)

**Comment by Andrey1994** [comment]
its a lot of work and you are the only requester of this feature, so I am not going to add it right now
